import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "ISTE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-anton min-h-screen flex flex-col justify-between">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
