import "./globals.css";

export const metadata = {
  title: "ISTE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-anton min-h-screen flex flex-col justify-between">
        {children}
      </body>
    </html>
  );
}
